### ISSUE TITLE
 Request for Access to N-Caltech and N-Cars Datasets

### ISSUE THREAD

**Issue by ChrisYu-Zz** [Wuziyi616/EventCLIP#4]
The N-Caltech and N-Cars datasets are no longer available for download. Could you please share these two datasets with me?

**Comment by Wuziyi616** [comment]
Due to license issues I don't think I'm allowed to redistribute the datasets. Maybe you can refer to the original website, e.g., [this one](https://www.garrickorchard.com/datasets/n-caltech101) for N-Caltech

**Comment by ChrisYu-Zz** [comment]
> Due to license issues I don't think I'm allowed to redistribute the datasets. Maybe you can refer to the original website, e.g., [this one](https://www.garrickorchard.com/datasets/n-caltech101) for N-Caltech

Thank you for your kind assistance and response!
