### ISSUE TITLE
How to complete visualization

### ISSUE THREAD

**Issue by disonmay** [Wuziyi616/EventCLIP#6]
Hello! Your work is extremely excellent and has been of great help to me. 
I have successfully run your train and test files and obtained the trained best.pth and verified accuracy and other information. However, I noticed that at the end of your paper, there are visualized results for classification (i.e., image display). May I ask how can I generate the visualized images?
![visual](https://github.com/user-attachments/assets/4626a94d-2d33-4eb8-ae26-af98361cd08d)

**Comment by Wuziyi616** [comment]
These results are obtained by transferring a open-world detector Detic to event data (as stated in the figure caption). They are not included in the main repo which focuses on a classification model CLIP. Unfortunately, there is no plan for releasing their code at the moment.
