### ISSUE TITLE
Restore event datasets to visual images

### ISSUE THREAD

**Issue by disonmay** [Wuziyi616/EventCLIP#7]
Thanks for your greatful work. 
Thank you very much for answering my previous  question. #6 
I would like to ask how to restoren event dataset to visualized images, that is, obtain the captured image represented by the event camera dataset.
It would be even better if there are relevant ideas and open-source codes.

**Comment by Wuziyi616** [comment]
There is no easy way to do this, as when you get events from images, you are losing information (e.g. RGB color information). There are some works in the event to video reconstruction field that try to reconstruct grayscale videos from events, which you may be interested. A famous work is [E2VID](https://github.com/uzh-rpg/rpg_e2vid).
